baseURL: 'https://raulcodes.com'
title: Raul Camacho
paginate: 5
theme: oso
languageCode: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: dev
          url: /tags/development
          weight: 5
        - name: music
          url: /tags/music
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: "tags"

paginate: 20

params:
  env: production

  # Available themes: gotham, toothpaste, dracula, gandalf, red-graphite
  colorTheme: red-graphite

  # Font family: IBM Plex, available styles: serif, sans
  fontStyle: sans

  plausible: true

  postProgress: true

  homePage:
    title: Howdy! 🤠
    description: I'm a full stack developer and hobby enthusiast. I write about code, music, design, and whatever else I find interesting!
    author: Raul Camacho
    pronouns: he/him
    avatar: pp_21.jpg

    socialIcons:
    - name: github
      url: 'https://github.com/raulcodes'
    - name: dribbble
      url: 'https://dribbble.com/raulcodes'
    # - name: twitter
      # url: 'https://twitter.com/_raulcodes'

  # ShowReadingTime: true
  # ShowShareButtons: false
  # comments: false

  assets:
    favicon: '/favicon.ico'
