baseURL: 'https://raulcodes.com'
title: Raul Camacho
paginate: 5
theme: oso
languageCode: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: development
          url: /tags/development
          weight: 5
        - name: music
          url: /tags/music
          weight: 10
        - name: literature
          url: /tags/literature
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: "tags"

paginate: 20

params:
  env: production

  # Available themes: gotham, toothpaste, dracula, gandalf, red-graphite, duotone-snow
  colorTheme: duotone-snow

  # Font family: IBM Plex, available styles: serif, sans
  fontStyle: sans

  # Background patterns: graph-paper, polka-dots, rain, texture, wiggle
  # Patterns available via heropatterns.com
  backgroundPatterns: rain

  # Adds JS
  plausible: true

  # Adds JS
  postProgress: true

  homePage:
    title: Howdy! 🤠
    description: I'm a full stack developer and hobby enthusiast. I write about code, music, design, and whatever else I find interesting!
    author: Raul Camacho
    pronouns: he/him
    avatar: pp_22.jpg

    newsletterNetlify: false

    socialIcons:
    - name: github
      url: 'https://github.com/raulcodes'
    - name: dev
      url: 'https://dribbble.com/raulcodes'
    # - name: twitter
      # url: 'https://twitter.com/_raulcodes'

  # ShowReadingTime: true
  # ShowShareButtons: false
  # comments: false

  assets:
    favicon: '/favicon.ico'
