baseURL: 'https://raulcodes.com'
title: Raul Camacho
paginate: 5
theme: hugo-papel

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: dev
          url: /tags/development
          weight: 5
        - name: music
          url: /tags/music
          weight: 10

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: "tags"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Raul Camacho
  description: Welcome to my blog
  author: Raul Camacho
  avatar: memoji.png

  # Available themes: gotham, toothpaste, dracula
  colorTheme: toothpaste

  # Font family: IBM Plex, available styles: serif, sans
  fontStyle: sans 

  # ShowReadingTime: true
  # ShowShareButtons: false
  # comments: false

  assets:
    favicon: '/favicon.ico'

  socialIcons:
    - name: github
      url: 'https://github.com/raulcodes'
    - name: dribbble
      url: 'https://dribbble.com/raulcodes'
    - name: twitter
      url: 'https://twitter.com/_raulcodes'

